### PR TITLE
Antony fix

### PR DESCRIPTION
**Pull request by eu-genia**

### CODE REVIEW

**Comment by DenisNosnitsin1970** [comment]
"Teaching" does not look like smth looking like Life of Anthony, and Getatchew's description of EMML 141 (accessible online) does not say that both are the same. 
grafik
If this was the case, He would know and he would certainly make a remark. (I do not see Gadla Entones anywhere among accessible texts, unfortunately).

**Comment by eu-genia** [comment]
You can of course check the MS but to me they are the same text.
Please read also https://www.academia.edu/4056138/Some_Remarks_Concerning_the_Ethiopic_Recension_of_the_Life_of_Antony_in_Orientalia_Christiana_Periodica_79_1_2013_37-60_in_English_
and the article by Witold in the volume you edited on the Veneration of Saints. 
See also the issue I created first.

**Comment by eu-genia** [comment]
EMML 7345 https://w3id.org/vhmml/readingRoom/view/200913
image

**Comment by eu-genia** [comment]
Nearly all EMML are in virtual reading room

**Comment by DenisNosnitsin1970** [comment]
I see, "Teaching" is endeed a slightly modified version of the Acts of Anthony.

**Comment by eu-genia** [comment]
can you then approve and merge? thank you

**Pull request merged**
