### PR TITLE
Gg ham

### PR DESCRIPTION
**Pull request by PietroLiuzzo**

### CODE REVIEW

**Comment by nafisa-valieva** [comment]
Ok!

**Review by nafisa-valieva — COMMENTED** [review]
I see some small errors, which we can tolerate at this point! In terms of structure, it seems to reflect our actual understanding of the dossier!

**Comment by PietroLiuzzo** [comment]
in the text? it is automatically transcribed, I would be surprised if it did not have any error...

**Comment by nafisa-valieva** [comment]
Thank you for your work! I think it is ready for merging!

**Comment by PietroLiuzzo** [comment]
I am still making the corrections you pointed out in the word file

**Pull request merged**
