### PR TITLE
deleted LIT5939CommCreed (=LIT5629AndemtaCreed), added relations

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by thea-m** [comment]
@PietroLiuzzo it is apparently not possible anymore to resolve conflicts in the web editor. I went on "open this in GitHub desktop", which opened this branch on GitHub desktop. If I open then one of the conlicted files in oxygen, I do not see any conflicts marked there. 
If it is necessary to work with the command line to resolve conflicts I will need a quick introduction.

**Comment by PietroLiuzzo** [comment]
these files [have been moved to another folder](https://github.com/BetaMasaheft/Works/pull/182), they are now in 5001-6000 in master. you made this pr first and the other one after, but that one got merged before. sorry about that, I should have looked out and not merge. please add a link in the description of the pr if you have pending prs affecting the same data. 
I think the easiest would be to simply switch to this branch, copy the changed files to your desktop, switch back to master, make a fresh new branch replicate the changes in the files in 5001-6000, pr that, which I will merge presently, close this pr and delete the old conflicted branch.

**Comment by PietroLiuzzo** [comment]
so this can be killed now?

**Comment by PietroLiuzzo** [comment]
why 9 here and 7 in the merged pr?

**Comment by Ralph-Lee-UK** [comment]
Am I right that you are asking @thea-m to do this?

**Comment by thea-m** [comment]
I only did the conflicted ones. I'll make new PR now for the other two.

@Ralph-Lee-UK yes, no worries!

**Comment by PietroLiuzzo** [comment]
@thea-m  thanks for the two prs, I did a late correction as a push to master from git directly... bad form... sorry! to you the honor to kill this!

**Comment by thea-m** [comment]
Goodbye, #167!

**Pull request closed without merging**
