### PR TITLE
Updated LIT7016Liton and added reference to it in LIT3188Liton

### PR DESCRIPTION
**Pull request by LeonardBahr**
Hello everyone.

My little project in updating all files with litanies to ensure uniformity and coherence once more faces a new step: 

Since the ID "CAe 7016" has been created a few months ago for a newly discovered litany based on its attestation in EMML 2109 in another issue (see https://github.com/BetaMasaheft/Documentation/issues/2561 and https://betamasaheft.eu/LIT7016Liton), I have now filled that tei/xml file with content like text, literature, and relations. I have also added the prayer to the General record of litanies (see https://betamasaheft.eu/LIT3188Liton). These are the two files which have been changed this time. Last time, the prayer was already added to the record for the seven weekdays (see https://betamasaheft.eu/LIT4860Litanies).

I would be grateful if you could have a look, approve and merge it.

Kind regards

Leo

### CODE REVIEW

**Review by eu-genia — APPROVED** [review]
looks good, thank you

**Review by CarstenHoffmannMarburg — APPROVED** [review]

**Comment by LeonardBahr** [comment]
Schalom everyone. As far as I can see the changes for https://betamasaheft.eu/LIT3188Liton were implemented, but the changes for https://betamasaheft.eu/LIT7016Liton have not. 

Is it normal to take some days or am I missing sth.?

**Comment by eu-genia** [comment]
thank you, fixed manually, the PR did not go through

**Comment by LeonardBahr** [comment]
Oh, that is so wonderful, thanks a million!

**Pull request merged**
