### PR TITLE
corrections

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
sorry @thea-m I cannot reconnect these to any conversation (too many I am afraid... sigh!) However, I have the feeling that this lawd:hasAttestation, linking a work and a manuscript I understand that there is an unspecified passage of the manuscript which mentions this work (i.e. indirectly or by title). is this what this means? if not I think we need to specify it with a desc for the future. what do you think?

**Comment by thea-m** [comment]
I'm sorry, I need to do a better job in general linking pull requests and issues...
Here, I looked at the last list of seven records mentioned in https://github.com/BetaMasaheft/Documentation/issues/1344 that were not reated elsewhere. 
As I understand the work-MS lawd:hasAttestation relations here, they are simply used to state that the work is contained in the manuscript. It is not something I would usually specify in a relation (because the work ID is used in the manuscript records), I kept it here not to lose the relation. Would it be better to delete it?

**Comment by PietroLiuzzo** [comment]
I understand. is this what we did also for the miracles of mary?

**Comment by thea-m** [comment]
Yes, that's it

**Comment by PietroLiuzzo** [comment]
I will document this usage in the GL.

**Pull request merged**
