### PR TITLE
Amharic admonitions (meedan) in BLorient11719 ch july24

### PR DESCRIPTION
**Pull request by CarstenHoffmannMarburg**
I created three unnecessary IDs as outlined in https://github.com/BetaMasaheft/Documentation/issues/2566.

### CODE REVIEW

**Comment by eu-genia** [comment]
You cannot create and delete something within the same pull request. 

A pull request is created from one branch. A branch is one copy of the whole set of folders.

If you first create a file in the folder and then delete a file in the folder this means no change as a result, as mathematically

x + 1 - 1 = x. nothing changed. 1-1=0

as you can see there are no files changed here at the moment. Please check what you are trying to do.

do the records you are trying to delete exist on the master branch? if yes create FROM MASTER a branch, delete them there, and launch a pull request.

they do not exist on master but are there on the app, meaning they were created but never merged?

create a pull request to merge them to master and then another one, from master, to delete them.

they do not exist on master but also not on the app any more?

that would mean they have already been deleted.

**Comment by CarstenHoffmannMarburg** [comment]
In this case, I assume, that I can delete this branch on my github desktop and in the list of "stale" branches?

**Comment by eu-genia** [comment]
No. You cannot.

You created the records in the application
image
but they are not on github.

You may never leave files out of synchronization. These files exist on the betamasaheft.eu application already. They do not exist in github.

This means you MUST synchronize the github repository to the application first by downloading and merging the records from branch number 1. In this specific case, changing to this branch on your github desktop you can in the branch history right-click on the deletion and revert the delete commit.
image Then the initial commit will be restored and the new records can be merged and synchronized.

Once the records have been synchronized, and the github file list of the MASTER branch is the same as the application file list you can create a new pull request from branch number 2 where you delete the erroneous records.

Closing and deleting this branch will NOT UPDATE THE APPLICATION betamasaheft.eu, as the two repositories are ONLY synchronized when pull requests are merged, they are not otherwise connected, the github cloud server is in the USA, the betamasaheft server is at the University of Hamburg.

**Comment by eu-genia** [comment]
I have now marked in bold the two lines in my original message in this conversation which are relevant for this case. You were supposed to check which case applies and act accordingly. Your case is the one marked in bold.

**Comment by eu-genia** [comment]
If you look at Commits you can see 
image

This is not allowed if IDs were created with the help of the app.

**Comment by CarstenHoffmannMarburg** [comment]
> This means you MUST synchronize the github repository to the application first by downloading and merging the records from branch number 1. In this specific case, changing to this branch on your github desktop you can in the branch history right-click on the deletion and revert the delete commit.
> image Then the initial commit will be restored and the new records can be merged and synchronized.

I reverted the deletion as you said. However, I was not able to push any pull request, because the github desktop answered, that I have made no changes. I did some small changes in order to be able to commit to this branch.

**Comment by eu-genia** [comment]
All good, now after the merge create a new pr from master  to delete

**Pull request merged**
