### PR TITLE
Update LIT1970Mashaf.xml

### PR DESCRIPTION
**Pull request by DenisNosnitsin1970**
New witnesses

### CODE REVIEW

**Comment by DariaElagina** [comment]
You mean that they are going to be used in the digital edition?

**Comment by DariaElagina** [comment]
Are those changes equal to those in the previous PR?

**Comment by DenisNosnitsin1970** [comment]
Maybe. What previous PR do you mean?

**Comment by DariaElagina** [comment]
According to the guideleines: We use <witness>↗ for those manuscripts which are used for the edition we are going to provide in the <div type='edition'>↗. 
I mean, #243

**Pull request merged**
