### PR TITLE
Hymn mary in mnc017

### PR DESCRIPTION
**Pull request by MassimoVilla**
Hymn attested in MNC017

### CODE REVIEW

**Comment by smaugustine** [comment]
If I'm not mistaken, this was edited by Sylvain Grébaut in _ROC_ 18 (1913), pp. 121-123. It also occurs, e.g., in Vat. et. 175. 

[Salam à la vierge Marie (S. Grébaut, 1913).pdf](https://github.com/BetaMasaheft/Works/files/5452470/Salam.a.la.vierge.Marie.S.Grebaut.1913.pdf)

**Comment by MassimoVilla** [comment]
Thank you so much @smaugustine ! There are some variants but both texts can be safely considered as one and the same work.

**Comment by smaugustine** [comment]
I believe in BM it is LIT4272Salam? It's a coincidence that right now I'm encoding Vat. et. 175 which also has it.

**Comment by MassimoVilla** [comment]
The text is already in the BM database as LIT4272Salam. Please ignore this PR, which I'll close right now.
Thank you again Augustine

**Comment by MassimoVilla** [comment]
Exactly, it's LIT4272Salam! What a coincidence!

**Pull request closed without merging**
