### PR TITLE
Create LIT6816MashafaSahay

### PR DESCRIPTION
**Pull request by CarstenHoffmannMarburg**
I created a new ID for Maṣḥafa Ṣ́aḥāy as discussed in issue [#2336](https://github.com/BetaMasaheft/Documentation/issues/2336). How can I add a hint to the known manuscripts EMML1389 and BMLacq38?

### CODE REVIEW

**Comment by eu-genia** [comment]
This is a doublet for LIT1982Mashaf

It should be deleted and the LIT1982Mashaf used instead

You can add a `msItem` with the ID to the relevant ms records and/or add `witness `in the work record https://betamasaheft.eu/Guidelines/?q=witness&start=6&id=work-teiHeader

**Comment by CarstenHoffmannMarburg** [comment]
Thank you and done.

**Comment by eu-genia** [comment]
I will merge this as is, and then it must be deleted with a new PR

**Comment by CarstenHoffmannMarburg** [comment]
What do you mean "delete with a new PR"? Can I delete with a right mouse click or shall I click on "Publish branch" first or shall I do another action before deleting this branch?

**Pull request merged**
