### PR TITLE
corrected title

### PR DESCRIPTION
**Pull request by thea-m**
Pull request out of principle, but let me know if you think it would be more appropriate to commit to master/merge the PR myself?

### CODE REVIEW

**Comment by thea-m** [comment]
Oh well, not so trivial maybe....;)

**Comment by thea-m** [comment]
Do you have access to the quoted reference? Is it for salus or Wednesday?

**Comment by eu-genia** [comment]
should be salus = Tuesday! Sorry!

**Comment by eu-genia** [comment]
I am going through the litanies and getting confused 
LIT4860Litanies has

```
<div type="textpart" subtype="chapter" xml:id="Monday" corresp="LIT1807Litonz">
                   <label>Litany for Monday</label>
               </div>
               <div type="textpart" subtype="chapter" xml:id="Tuesday" corresp="LIT4858Litany">
                   <label>Litany for Tuesday</label>
               </div>
               <div type="textpart" subtype="chapter" xml:id="Wednesday" corresp="LIT4859Litany">
                   <label>Litany for Wednesday</label>
               </div>
               <div type="textpart" subtype="chapter" xml:id="Thursday" corresp="LIT4264Salota">
                   <label>Litany for Thursday</label>
               </div>
               <div type="textpart" subtype="chapter" xml:id="Friday" corresp="LIT4266Litonz">
                   <label>Litany for Friday</label>
               </div>
               <div type="textpart" subtype="chapter" xml:id="Saturday" corresp="LIT4265Litonz">
                   <label>Litany for Saturday</label>
               </div>
               <div type="textpart" subtype="chapter" xml:id="Sunday" corresp="LIT4268Tazakkar">
                   <label>Litany for Sunday</label>
               </div>
```
4858 is given correctly as Tuesday here but what about LIT4859Litany? Here it is listed for Wednesday but the file says Sunday... (It is also used for Sunday correctly, but probably the Wednesday is simply missing? Can find no record for the Wednesday)

**Comment by eu-genia** [comment]
no wait for Sunday it has LIT4268Tazakkar - is this correct?

**Comment by thea-m** [comment]
As I wrote in my mail (which you did probably not read because I wrote you not to read it, very smart of me...) there is a lot of chaos in this. I was planning to go over them, but if you want to do it, feel free.    But we should decide who does it. (We have the text for these typed by Leo, which I was about to add to the LIT4860Litanies  record)

**Comment by eu-genia** [comment]
oops sorry did not get through to the mail yet :) 
would be great if you could fix this (then scream as I have then mss records to fix)

the text - should it be added to LIT4860Litanies or to single records?

**Comment by thea-m** [comment]
Good, then I'll do it in the next days. The manuscripts will be even more chaotic...but the only way is forward.
I wasn't sure about whether to add it to the common or individual records either - what do you think? I just did not add it to maṣḥafa qəddāse, because the record is very unübersichtlich already, so I thought it would be better in a separate one, with reference.

**Comment by eu-genia** [comment]
I think as long as single records exist the text belongs with them (?)

**Comment by thea-m** [comment]
I'm not aware of a general rule (?), but it's fine, I'll add a note to the common record then.

**Pull request merged**
