### PR TITLE
Create LIT6553SacerPrayers.xml

### PR DESCRIPTION
**Pull request by DenisNosnitsin1970**
New record

### CODE REVIEW

**Review by thea-m — CHANGES_REQUESTED** [review]
Could you maybe add the bibliographic reference from which the designation is taken (Velat, I bleieve)?

**Comment by eu-genia** [comment]
Agree, maybe adding to the abstract "referred to as priéres sacerdotales in `<bibl><ptr target="bm:Velat1966MeerafTrad"/><citedRange>161</citedRange></bibl>`" could be helpful to understand the term; one could also add other terms if such were used somewhere (how does Habtemichael call them, if he groups them at all?)

**Comment by DenisNosnitsin1970** [comment]
The appearance of Velat in the discussion above is accidental. The major issue is the way of  classifying the content of "Mashafa qeddase" into three main parts (Daily prayers; Ser'ata qeddase; Anaphoras). I followed the practice of Getatchew Haile who grouped the mentioned items together; he called them like this, but only in the EMML I (I can certainly mention him in the bibliography; later in the same volume and futher he changed to somewhat ambiguous but economic "Office prayers"). Some catalogues do group the items together (Wright) using various designations (I would prefer that way), some treat them separately (VOHD, four parts, or others).

**Comment by DenisNosnitsin1970** [comment]
Well, formally the author of EMML I was Macomber :)

**Pull request merged**
