### PR TITLE
new records, specifications

### PR DESCRIPTION
**Pull request by thea-m**
edits related to the Psalter and BLadd19960
I would be happy for a better title alternative than "Non-typical Psalter"...

### CODE REVIEW

**Comment by thea-m** [comment]
(I'm not sure whether we're allowed to merge already? Maybe I missed a mail)

**Comment by thea-m** [comment]
https://github.com/BetaMasaheft/Documentation/issues/1359

**Comment by thea-m** [comment]
(sorry, I am done committing to this branch now!)

**Comment by PietroLiuzzo** [comment]
no, you are not allowed, no email was sent about that yet, it will come soon hopefully.

**Comment by thea-m** [comment]
@DenisNosnitsin1970 @DariaElagina

**Comment by thea-m** [comment]
Anyone? :)

**Comment by eu-genia** [comment]
Psalter (alternative) ?

**Pull request merged**
