### PR TITLE
Magic Prayer against terror and for subduing devils (ጸሎተ፡ ድንጋፄ፡ ወመግረሬ፡ አጋንንት፡) in BLorient5425

### PR DESCRIPTION
**Pull request by CarstenHoffmannMarburg**
According to our discussion in https://github.com/BetaMasaheft/Documentation/issues/2626.

I created another ID by mistake (LIT7104PrayDengatse) in another new branch. I will delete this ID on my computer and delete this branch, so it will make no trouble in the app.

### CODE REVIEW

**Comment by eu-genia** [comment]
just to make sure that we are talking about the same thing:

if you created a CAe ID in the app you must first have it merged and then create an additional PR to delete as otherwise it will stay in the system. so the normal workflow is: 
(1) have both IDs merged (one can be a developed file and one remain a stub, but it must be merged anyway), they can be both committed and merged in the same branch in one PR
(2) sync your github desktop to the master after the successful merge
(3) create a new branch and pull request to delete the redundant ID

**Comment by eu-genia** [comment]
NB only merged (or otherwise unnecessary and errouneously created) branches should be deleted. 
deleting branch does not delete anything in the web app, only in github.

at the same time one should make sure that all the branches that one has created are eventually merged (and deleted) - we keep accumulating branches that it is difficult to see if they are still in use. 

you can check e.g. here 
https://github.com/BetaMasaheft/Manuscripts/branches/yours
https://github.com/BetaMasaheft/Works/branches/yours
etc for all the branches you have created

image

**Review by eu-genia — APPROVED** [review]

**Review by karljonaskarlsson — APPROVED** [review]

**Comment by CarstenHoffmannMarburg** [comment]
> just to make sure that we are talking about the same thing:
> 
> if you created a CAe ID in the app you must first have it merged and then create an additional PR to delete as otherwise it will stay in the system. so the normal workflow is: (1) have both IDs merged (one can be a developed file and one remain a stub, but it must be merged anyway), they can be both committed and merged in the same branch in one PR (2) sync your github desktop to the master after the successful merge (3) create a new branch and pull request to delete the redundant ID

I found the branch PrayDengatse_CH in Github desctop (even though I thought, that I have already deleted it). However, I cannot find the file LIT7104PrayDengatse in the BetMas folder any more.

**Comment by eu-genia** [comment]
Sorry now I see that PrayerDengatse_CH branch is the one for LIT7096Dengatse so it is safe to delete it. I do not know if there is a branch with LIT7104PrayDengatse.

**Comment by eu-genia** [comment]
Since LIT7104PrayDengatse was never properly committed or merged it clearly could not be deleted so if it must be deleted then 

1) download LIT7104PrayDengatse  from betamasaheft.eu 
2) create a pull request to merge it (even if it will be temporary)
3) after it has been merged to master - delete it and create a new pull request to delete it
4) done 

thank you!

**Comment by CarstenHoffmannMarburg** [comment]
Dear Eugenia,


I had again a problem with the internet connection and I was logged out, when creating a new LIT ID. I wanted to recover it from the Bm website by typing the LIT ID plus .xml in the adress, but it did not work out. Can I recover LIT7116Respect?


Sorry for bothering you with many issues of this kind!


[cid:387d78fe-995c-4f2f-aa9f-6cfe5df6f7b8]

________________________________
Von: Eugenia ***@***.***>
Gesendet: Montag, 21. Oktober 2024 09:21
An: BetaMasaheft/Works
Cc: Hoffmann, Dr. Carsten; State change
Betreff: Re: [BetaMasaheft/Works] Magic Prayer against terror and for subduing devils (ጸሎተ፡ ድንጋፄ፡ ወመግረሬ፡ አጋንንት፡) in BLorient5425 (PR #1246)


Since LIT7104PrayDengatse was never properly committed or merged it clearly could not be deleted so if it must be deleted then

  1.  download LIT7104PrayDengatse from betamasaheft.eu
  2.  create a pull request to merge it (even if it will be temporary)
  3.  after it has been merged to master - delete it and create a new pull request to delete it
  4.  done

thank you!

**Pull request merged**
