### PR TITLE
Prayer to jesus christ

### PR DESCRIPTION
**Pull request by DariaElagina**

### CODE REVIEW

**Comment by thea-m** [comment]
I assume that this is a record for a work described in a catalogue as "Prayer to Jesus Christ" without any text or further information given :)

**Comment by DariaElagina** [comment]
there is a portion of text, but not an incipit. The search for this text brought no results...

**Comment by thea-m** [comment]
sorry for double comment, just ignore it

**Comment by thea-m** [comment]
Will the text be given in the manuscript record?

**Comment by DariaElagina** [comment]
sure

**Pull request merged**
